# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get the version
        id: tag_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build project # This would actually build your project, using zip for an example artifact
        run: zip -r ${{ steps.tag_version.outputs.VERSION }}.zip . -x ".git/*" ".github/*" ".editorconfig" ".gitignore"

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
